// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqxxfKzoOdyifcj3DQW1FD7TfCjJJwGs0',
    appId: '1:934098347205:web:c74d3a3c341c296fa03cac',
    messagingSenderId: '934098347205',
    projectId: 'chitral-dost',
    authDomain: 'chitral-dost.firebaseapp.com',
    storageBucket: 'chitral-dost.firebasestorage.app',
    measurementId: 'G-S72KQGMWWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEqsmGxPju4pj4kKiOrjELolWpXClyk6U',
    appId: '1:934098347205:android:1a5404a939f4f168a03cac',
    messagingSenderId: '934098347205',
    projectId: 'chitral-dost',
    storageBucket: 'chitral-dost.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHMN68xTIpcniy_Zs-DvlyLhNs4kG2qZY',
    appId: '1:934098347205:ios:65208f40e294f553a03cac',
    messagingSenderId: '934098347205',
    projectId: 'chitral-dost',
    storageBucket: 'chitral-dost.firebasestorage.app',
    iosBundleId: 'com.example.chitralDostApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHMN68xTIpcniy_Zs-DvlyLhNs4kG2qZY',
    appId: '1:934098347205:ios:65208f40e294f553a03cac',
    messagingSenderId: '934098347205',
    projectId: 'chitral-dost',
    storageBucket: 'chitral-dost.firebasestorage.app',
    iosBundleId: 'com.example.chitralDostApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqxxfKzoOdyifcj3DQW1FD7TfCjJJwGs0',
    appId: '1:934098347205:web:002870efa3995d44a03cac',
    messagingSenderId: '934098347205',
    projectId: 'chitral-dost',
    authDomain: 'chitral-dost.firebaseapp.com',
    storageBucket: 'chitral-dost.firebasestorage.app',
    measurementId: 'G-BKMZYFFT2Z',
  );

}